repository: Navi
repository_url: https://github.com/mingjun90/Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 星星导航
alias: 星星导航
description: A Navigation Website
keywords: Navi, Navigation
url: http://127.0.0.1

author: Navi
author_url: https://github.com/mingjun90/Navi
organization: LLab
organization_url: https://github.com/mingjun90
contact: mingjun[dot]carl[dot]li[at]gmail[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.png
logo_white: /images/logo-white.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
- navi.sh
